import type { ArchitectureDocument } from "../types/architecture";

export const sampleArchitecture: ArchitectureDocument = {
    nodes: [
        {
            id: "gateway",
            type: "api_gateway",
            trust_level: "external",
            label: "Public Gateway",
            exposes_public_endpoint: true,
            accepts_untrusted_input: true,
            tags: [],
        },
        {
            id: "auth",
            type: "auth_service",
            trust_level: "internal",
            label: "Auth Service",
            auth: "jwt",
            authorization: "role based",
            exposes_public_endpoint: false,
            accepts_untrusted_input: false,
            tags: [],
        },
        {
            id: "billing",
            type: "microservice",
            trust_level: "internal",
            label: "Billing Service",
            auth: "jwt",
            authorization: "role based",
            exposes_public_endpoint: false,
            accepts_untrusted_input: false,
            tags: [],
        },
        {
            id: "worker",
            type: "background_worker",
            trust_level: "privileged",
            label: "Background Worker",
            auth: "serviceaccount",
            exposes_public_endpoint: false,
            accepts_untrusted_input: false,
            tags: [],
        },
        {
            id: "database",
            type: "database",
            trust_level: "restricted",
            label: "Database",
            exposes_public_endpoint: false,
            accepts_untrusted_input: false,
            tags: [],
        },
    ],
    edges: [
        {
            from: "gateway",
            to: "auth",
            protocol: "https",
            carries_identity: true,
            transforms_input: false,
            queue: false,
        },
        {
            from: "auth",
            to: "billing",
            protocol: "https",
            carries_identity: true,
            transforms_input: false,
            queue: false,
        },
        {
            from: "billing",
            to: "worker",
            protocol: "queue",
            carries_identity: false,
            transforms_input: false,
            queue: true,
        },
        {
            from: "worker",
            to: "database",
            protocol: "postgres",
            carries_identity: false,
            transforms_input: false,
            queue: false,
        },
    ],
    metadata: {},
};
